In [14]:
import polars as pl

pl.Config.set_tbl_cols(-1)      # Show all columns
pl.Config.set_tbl_rows(20)      # Optional: show more rows
pl.Config.set_tbl_width_chars(800)  # Increase table width

polars.config.Config

In [15]:
import polars as pl

routes = [
    "M1",
    "M2",
    "M4",
    "M15",
    "M101"
]

url = (
    "http://parquet.gtfsrt.io/vehicle_positions"
    "/date=2026-07-01"
    "/base64url=aHR0cHM6Ly9ndGZzcnQucHJvZC5vYmFueWMuY29tL3ZlaGljbGVQb3NpdGlvbnM"
    "/data.parquet"
)

df = (
    pl.scan_parquet(url)
      .filter(pl.col("route_id").is_in(routes))
      .select([
      "trip_id",
      "route_id",
      "vehicle_id",
      "direction_id",
    #   "start_time",
      "start_date",
    #   "vehicle_label",
      "latitude",
      "longitude",
      "bearing",
      "stop_id",
      "timestamp"
  ])

      .collect(engine="streaming")
)

print(df.shape)
print(df.head())

(213659, 10)
shape: (5, 10)
┌─────────────────────────────┬──────────┬───────────────┬──────────────┬────────────┬───────────┬────────────┬────────────┬─────────┬────────────┐
│ trip_id                     ┆ route_id ┆ vehicle_id    ┆ direction_id ┆ start_date ┆ latitude  ┆ longitude  ┆ bearing    ┆ stop_id ┆ timestamp  │
│ ---                         ┆ ---      ┆ ---           ┆ ---          ┆ ---        ┆ ---       ┆ ---        ┆ ---        ┆ ---     ┆ ---        │
│ str                         ┆ str      ┆ str           ┆ u32          ┆ str        ┆ f32       ┆ f32        ┆ f32        ┆ str     ┆ u64        │
╞═════════════════════════════╪══════════╪═══════════════╪══════════════╪════════════╪═══════════╪════════════╪════════════╪═════════╪════════════╡
│ MV_C6-Weekday-119400_M4_434 ┆ M4       ┆ MTA NYCT_9771 ┆ 1            ┆ 20260630   ┆ 40.845314 ┆ -73.940529 ┆ 247.760437 ┆ 400648  ┆ 1782863966 │
│ MV_C6-Weekday-114100_M4_433 ┆ M4       ┆ MTA NYCT_9775 ┆ 0            ┆ 20260630   ┆ 40.820766 ┆ -73.954453 ┆ 51.340191  ┆ 400609  ┆ 1782863976 │
│ MV_C6-Weekday-117300_M4_436 ┆ M4       ┆ MTA NYCT_9779 ┆ 1            ┆ 20260630   ┆ 40.82238  ┆ -73.953514 ┆ 233.92572  ┆ 400663  ┆ 1782863986 │
│ MV_C6-Weekday-120000_M4_431 ┆ M4       ┆ MTA NYCT_9778 ┆ 0            ┆ 20260630   ┆ 40.747314 ┆ -73.983276 ┆ 54.381512  ┆ 400354  ┆ 1782863970 │
│ MV_C6-Weekday-118700_M5_537 ┆ M4       ┆ MTA NYCT_9776 ┆ 1            ┆ 20260630   ┆ 40.837948 ┆ -73.943947 ┆ 248.20694  ┆ 403376  ┆ 1782863994 │
└─────────────────────────────┴──────────┴───────────────┴──────────────┴────────────┴───────────┴────────────┴────────────┴─────────┴────────────┘

In [16]:
df.null_count()

shape: (1, 10)
┌─────────┬──────────┬────────────┬──────────────┬────────────┬──────────┬───────────┬─────────┬─────────┬───────────┐
│ trip_id ┆ route_id ┆ vehicle_id ┆ direction_id ┆ start_date ┆ latitude ┆ longitude ┆ bearing ┆ stop_id ┆ timestamp │
│ ---     ┆ ---      ┆ ---        ┆ ---          ┆ ---        ┆ ---      ┆ ---       ┆ ---     ┆ ---     ┆ ---       │
│ u32     ┆ u32      ┆ u32        ┆ u32          ┆ u32        ┆ u32      ┆ u32       ┆ u32     ┆ u32     ┆ u32       │
╞═════════╪══════════╪════════════╪══════════════╪════════════╪══════════╪═══════════╪═════════╪═════════╪═══════════╡
│ 0       ┆ 0        ┆ 0          ┆ 0            ┆ 0          ┆ 0        ┆ 0         ┆ 0       ┆ 0       ┆ 0         │
└─────────┴──────────┴────────────┴──────────────┴────────────┴──────────┴───────────┴─────────┴─────────┴───────────┘

In [17]:
df.write_parquet(
    "raw/vehicle_positions/2026-07-01.parquet"
)

In [18]:
import polars as pl

routes = [
    "M1",
    "M2",
    "M4",
    "M15",
    "M101"
]

url = (
    "http://parquet.gtfsrt.io/trip_updates"
    "/date=2026-07-01"
    "/base64url=aHR0cHM6Ly9ndGZzcnQucHJvZC5vYmFueWMuY29tL3RyaXBVcGRhdGVz"
    "/data.parquet"
)

df = (
    pl.scan_parquet(url)
      .filter(pl.col("route_id").is_in(routes))
      .select([
        "feed_timestamp",
        "fetch_timestamp",
        "trip_id",
        "route_id",
        "direction_id",
        "start_time",
        "start_date",
        "schedule_relationship",
        "vehicle_id",
        "trip_timestamp",
        "stop_sequence",
        "stop_id",
        "arrival_time",
        "departure_time"
  ])

      .collect(engine="streaming")
)

print(df.shape)
print(df.head())

(8209429, 14)
shape: (5, 14)
┌────────────────┬────────────────────────────────┬─────────────────────────────┬──────────┬──────────────┬────────────┬────────────┬───────────────────────┬───────────────┬────────────────┬───────────────┬─────────┬──────────────┬────────────────┐
│ feed_timestamp ┆ fetch_timestamp                ┆ trip_id                     ┆ route_id ┆ direction_id ┆ start_time ┆ start_date ┆ schedule_relationship ┆ vehicle_id    ┆ trip_timestamp ┆ stop_sequence ┆ stop_id ┆ arrival_time ┆ departure_time │
│ ---            ┆ ---                            ┆ ---                         ┆ ---      ┆ ---          ┆ ---        ┆ ---        ┆ ---                   ┆ ---           ┆ ---            ┆ ---           ┆ ---     ┆ ---          ┆ ---            │
│ u64            ┆ datetime[μs, UTC]              ┆ str                         ┆ str      ┆ u32          ┆ str        ┆ str        ┆ i32                   ┆ str           ┆ u64            ┆ u32           ┆ str     ┆ i64          ┆ i64            │
╞════════════════╪════════════════════════════════╪═════════════════════════════╪══════════╪══════════════╪════════════╪════════════╪═══════════════════════╪═══════════════╪════════════════╪═══════════════╪═════════╪══════════════╪════════════════╡
│ 1782864003     ┆ 2026-07-01 00:00:28.366841 UTC ┆ MV_C6-Weekday-119400_M4_434 ┆ M4       ┆ 1            ┆            ┆ 20260630   ┆ 0                     ┆ MTA NYCT_9771 ┆ 1782863996     ┆ 9             ┆ 400647  ┆ 1782863997   ┆ 1782863997     │
│ 1782864003     ┆ 2026-07-01 00:00:28.366841 UTC ┆ MV_C6-Weekday-119400_M4_434 ┆ M4       ┆ 1            ┆            ┆ 20260630   ┆ 0                     ┆ MTA NYCT_9771 ┆ 1782863996     ┆ 10            ┆ 400648  ┆ 1782864060   ┆ 1782864060     │
│ 1782864003     ┆ 2026-07-01 00:00:28.366841 UTC ┆ MV_C6-Weekday-119400_M4_434 ┆ M4       ┆ 1            ┆            ┆ 20260630   ┆ 0                     ┆ MTA NYCT_9771 ┆ 1782863996     ┆ 11            ┆ 400649  ┆ 1782864114   ┆ 1782864114     │
│ 1782864003     ┆ 2026-07-01 00:00:28.366841 UTC ┆ MV_C6-Weekday-119400_M4_434 ┆ M4       ┆ 1            ┆            ┆ 20260630   ┆ 0                     ┆ MTA NYCT_9771 ┆ 1782863996     ┆ 12            ┆ 403373  ┆ 1782864183   ┆ 1782864183     │
│ 1782864003     ┆ 2026-07-01 00:00:28.366841 UTC ┆ MV_C6-Weekday-119400_M4_434 ┆ M4       ┆ 1            ┆            ┆ 20260630   ┆ 0                     ┆ MTA NYCT_9771 ┆ 1782863996     ┆ 13            ┆ 403374  ┆ 1782864280   ┆ 1782864280     │
└────────────────┴────────────────────────────────┴─────────────────────────────┴──────────┴──────────────┴────────────┴────────────┴───────────────────────┴───────────────┴────────────────┴───────────────┴─────────┴──────────────┴────────────────┘

In [19]:
df.write_parquet(
    "raw/trip_updates/2026-07-01.parquet"
)

In [20]:
import polars as pl

url = (
    "http://parquet.gtfsrt.io/service_alerts"
    "/date=2026-07-01"
    "/base64url=aHR0cHM6Ly9ndGZzcnQucHJvZC5vYmFueWMuY29tL2FsZXJ0cw"
    "/data.parquet"
)

df = (
    pl.scan_parquet(url)
    .select([
        "feed_timestamp",
        "fetch_timestamp",
        "entity_id",
        "active_period_start",
        "active_period_end",
        "header_text",
        "description_text",
        "url",
        "route_id",
        "route_type",
        "stop_id",
        "trip_id",
        "trip_route_id",
        "trip_direction_id"
    ])
    .collect(engine="streaming")
)

print(df.shape)
print(df.head())

(208877, 14)
shape: (5, 14)
┌────────────────┬────────────────────────────────┬─────────────────────────────────┬─────────────────────┬───────────────────┬─────────────────────────────────┬─────────────────────────────────┬──────┬──────────┬────────────┬─────────┬─────────┬───────────────┬───────────────────┐
│ feed_timestamp ┆ fetch_timestamp                ┆ entity_id                       ┆ active_period_start ┆ active_period_end ┆ header_text                     ┆ description_text                ┆ url  ┆ route_id ┆ route_type ┆ stop_id ┆ trip_id ┆ trip_route_id ┆ trip_direction_id │
│ ---            ┆ ---                            ┆ ---                             ┆ ---                 ┆ ---               ┆ ---                             ┆ ---                             ┆ ---  ┆ ---      ┆ ---        ┆ ---     ┆ ---     ┆ ---           ┆ ---               │
│ u64            ┆ datetime[μs, UTC]              ┆ str                             ┆ u64                 ┆ u64               ┆ str                             ┆ str                             ┆ str  ┆ str      ┆ i32        ┆ str     ┆ str     ┆ str           ┆ u32               │
╞════════════════╪════════════════════════════════╪═════════════════════════════════╪═════════════════════╪═══════════════════╪═════════════════════════════════╪═════════════════════════════════╪══════╪══════════╪════════════╪═════════╪═════════╪═══════════════╪═══════════════════╡
│ 1782863956     ┆ 2026-07-01 00:00:20.367223 UTC ┆ MTA NYCT_lmm:planned_work:2224… ┆ 1735880435          ┆ 1798415688        ┆ X28&#x200c; and &#x200c;X38&#x… ┆ X28&#x200c; and &#x200c;X38&#x… ┆ null ┆ X38      ┆ null       ┆ null    ┆ null    ┆ null          ┆ null              │
│ 1782863956     ┆ 2026-07-01 00:00:20.367223 UTC ┆ MTA NYCT_lmm:planned_work:2224… ┆ 1735880435          ┆ 1798415688        ┆ X28&#x200c; and &#x200c;X38&#x… ┆ X28&#x200c; and &#x200c;X38&#x… ┆ null ┆ X28      ┆ null       ┆ null    ┆ null    ┆ null          ┆ null              │
│ 1782863956     ┆ 2026-07-01 00:00:20.367223 UTC ┆ MTA NYCT_lmm:planned_work:2781… ┆ 1769058000          ┆ 1798415688        ┆ Westbound M66 stop on E 68th S… ┆ Westbound M66 stop on E 68th S… ┆ null ┆ null     ┆ null       ┆ null    ┆         ┆ M66           ┆ 1                 │
│ 1782863956     ┆ 2026-07-01 00:00:20.367223 UTC ┆ MTA NYCT_lmm:planned_work:2781… ┆ 1769058000          ┆ 1798415688        ┆ Westbound M66 stop on E 68th S… ┆ Westbound M66 stop on E 68th S… ┆ null ┆ null     ┆ null       ┆ null    ┆         ┆ M66           ┆ 0                 │
│ 1782863956     ┆ 2026-07-01 00:00:20.367223 UTC ┆ MTA NYCT_lmm:planned_work:3082… ┆ 1774497600          ┆ 1798415688        ┆ Southbound B16 stops on 13th A… ┆ Southbound B16 stops on 13th A… ┆ null ┆ null     ┆ null       ┆ null    ┆         ┆ B16           ┆ 0                 │
└────────────────┴────────────────────────────────┴─────────────────────────────────┴─────────────────────┴───────────────────┴─────────────────────────────────┴─────────────────────────────────┴──────┴──────────┴────────────┴─────────┴─────────┴───────────────┴───────────────────┘

In [21]:
df.null_count()

shape: (1, 14)
┌────────────────┬─────────────────┬───────────┬─────────────────────┬───────────────────┬─────────────┬──────────────────┬────────┬──────────┬────────────┬─────────┬─────────┬───────────────┬───────────────────┐
│ feed_timestamp ┆ fetch_timestamp ┆ entity_id ┆ active_period_start ┆ active_period_end ┆ header_text ┆ description_text ┆ url    ┆ route_id ┆ route_type ┆ stop_id ┆ trip_id ┆ trip_route_id ┆ trip_direction_id │
│ ---            ┆ ---             ┆ ---       ┆ ---                 ┆ ---               ┆ ---         ┆ ---              ┆ ---    ┆ ---      ┆ ---        ┆ ---     ┆ ---     ┆ ---           ┆ ---               │
│ u32            ┆ u32             ┆ u32       ┆ u32                 ┆ u32               ┆ u32         ┆ u32              ┆ u32    ┆ u32      ┆ u32        ┆ u32     ┆ u32     ┆ u32           ┆ u32               │
╞════════════════╪═════════════════╪═══════════╪═════════════════════╪═══════════════════╪═════════════╪══════════════════╪════════╪══════════╪════════════╪═════════╪═════════╪═══════════════╪═══════════════════╡
│ 0              ┆ 0               ┆ 0         ┆ 0                   ┆ 25622             ┆ 0           ┆ 0                ┆ 208877 ┆ 152314   ┆ 208877     ┆ 208877  ┆ 56563   ┆ 56563         ┆ 56563             │
└────────────────┴─────────────────┴───────────┴─────────────────────┴───────────────────┴─────────────┴──────────────────┴────────┴──────────┴────────────┴─────────┴─────────┴───────────────┴───────────────────┘

In [22]:
df.write_parquet(
    "raw/service_alerts/2026-07-01.parquet"
)