In [84]:
import polars as pl

pl.Config.set_tbl_cols(-1)      # Show all columns
pl.Config.set_tbl_rows(20)      # Optional: show more rows
pl.Config.set_tbl_width_chars(800)  # Increase table width

polars.config.Config

In [85]:
import polars as pl

routes = [
    "Q17",
    "Q24",
    "Q27",
    "Q30",
    "Q31",
]

url = (
    "http://parquet.gtfsrt.io/vehicle_positions"
    "/date=2026-07-01"
    "/base64url=aHR0cHM6Ly9ndGZzcnQucHJvZC5vYmFueWMuY29tL3ZlaGljbGVQb3NpdGlvbnM"
    "/data.parquet"
)

df = (
    pl.scan_parquet(url)
      .filter(pl.col("route_id").is_in(routes))
      .select([
      "trip_id",
      "route_id",
      "vehicle_id",
      "direction_id",
    #   "start_time",
      "start_date",
    #   "vehicle_label",
      "latitude",
      "longitude",
      "bearing",
      "stop_id",
      "timestamp"
  ])

      .collect(engine="streaming")
)

print(df.shape)
print(df.head())

(132703, 10)
shape: (5, 10)
┌───────────────────────────────┬──────────┬───────────────┬──────────────┬────────────┬───────────┬────────────┬────────────┬─────────┬────────────┐
│ trip_id                       ┆ route_id ┆ vehicle_id    ┆ direction_id ┆ start_date ┆ latitude  ┆ longitude  ┆ bearing    ┆ stop_id ┆ timestamp  │
│ ---                           ┆ ---      ┆ ---           ┆ ---          ┆ ---        ┆ ---       ┆ ---        ┆ ---        ┆ ---     ┆ ---        │
│ str                           ┆ str      ┆ str           ┆ u32          ┆ str        ┆ f32       ┆ f32        ┆ f32        ┆ str     ┆ u64        │
╞═══════════════════════════════╪══════════╪═══════════════╪══════════════╪════════════╪═══════════╪════════════╪════════════╪═════════╪════════════╡
│ JA_C6-Weekday-118200_Q17_314  ┆ Q17      ┆ MTA NYCT_8440 ┆ 1            ┆ 20260630   ┆ 40.738144 ┆ -73.805496 ┆ 357.220825 ┆ 501388  ┆ 1782863972 │
│ JA_C6-Weekday-118400_MISC_850 ┆ Q30      ┆ MTA NYCT_8434 ┆ 1            ┆ 20260630   ┆ 40.731159 ┆ -73.793854 ┆ 274.398712 ┆ 501505  ┆ 1782863985 │
│ JA_C6-Weekday-118600_MISC_854 ┆ Q17      ┆ MTA NYCT_8435 ┆ 1            ┆ 20260630   ┆ 40.747269 ┆ -73.815437 ┆ 317.960938 ┆ 501379  ┆ 1782863973 │
│ EN_C6-Weekday-113100_B15_156  ┆ Q24      ┆ MTA NYCT_7139 ┆ 1            ┆ 20260630   ┆ 40.680218 ┆ -73.905785 ┆ 149.858612 ┆ 301977  ┆ 1782863982 │
│ JA_C6-Weekday-117800_MISC_849 ┆ Q17      ┆ MTA NYCT_8468 ┆ 1            ┆ 20260630   ┆ 40.738171 ┆ -73.806259 ┆ 358.246582 ┆ 501388  ┆ 1782863973 │
└───────────────────────────────┴──────────┴───────────────┴──────────────┴────────────┴───────────┴────────────┴────────────┴─────────┴────────────┘

In [86]:
df.null_count()

shape: (1, 10)
┌─────────┬──────────┬────────────┬──────────────┬────────────┬──────────┬───────────┬─────────┬─────────┬───────────┐
│ trip_id ┆ route_id ┆ vehicle_id ┆ direction_id ┆ start_date ┆ latitude ┆ longitude ┆ bearing ┆ stop_id ┆ timestamp │
│ ---     ┆ ---      ┆ ---        ┆ ---          ┆ ---        ┆ ---      ┆ ---       ┆ ---     ┆ ---     ┆ ---       │
│ u32     ┆ u32      ┆ u32        ┆ u32          ┆ u32        ┆ u32      ┆ u32       ┆ u32     ┆ u32     ┆ u32       │
╞═════════╪══════════╪════════════╪══════════════╪════════════╪══════════╪═══════════╪═════════╪═════════╪═══════════╡
│ 0       ┆ 0        ┆ 0          ┆ 0            ┆ 0          ┆ 0        ┆ 0         ┆ 0       ┆ 0       ┆ 0         │
└─────────┴──────────┴────────────┴──────────────┴────────────┴──────────┴───────────┴─────────┴─────────┴───────────┘

In [87]:
df.write_parquet(
    "raw/vehicle_positions/2026-07-01.parquet"
)

In [88]:
import polars as pl

routes = [
    "Q17",
    "Q24",
    "Q27",
    "Q30",
    "Q31",
]

url = (
    "http://parquet.gtfsrt.io/trip_updates"
    "/date=2026-07-01"
    "/base64url=aHR0cHM6Ly9ndGZzcnQucHJvZC5vYmFueWMuY29tL3RyaXBVcGRhdGVz"
    "/data.parquet"
)

df = (
    pl.scan_parquet(url)
      .filter(pl.col("route_id").is_in(routes))
      .select([
        "feed_timestamp",
        "fetch_timestamp",
        "trip_id",
        "route_id",
        "direction_id",
        "start_time",
        "start_date",
        "schedule_relationship",
        "vehicle_id",
        "trip_timestamp",
        "stop_sequence",
        "stop_id",
        "arrival_time",
        "departure_time"
  ])

      .collect(engine="streaming")
)

print(df.shape)
print(df.head())

(3851145, 14)
shape: (5, 14)
┌────────────────┬────────────────────────────────┬──────────────────────────────┬──────────┬──────────────┬────────────┬────────────┬───────────────────────┬───────────────┬────────────────┬───────────────┬─────────┬──────────────┬────────────────┐
│ feed_timestamp ┆ fetch_timestamp                ┆ trip_id                      ┆ route_id ┆ direction_id ┆ start_time ┆ start_date ┆ schedule_relationship ┆ vehicle_id    ┆ trip_timestamp ┆ stop_sequence ┆ stop_id ┆ arrival_time ┆ departure_time │
│ ---            ┆ ---                            ┆ ---                          ┆ ---      ┆ ---          ┆ ---        ┆ ---        ┆ ---                   ┆ ---           ┆ ---            ┆ ---           ┆ ---     ┆ ---          ┆ ---            │
│ u64            ┆ datetime[μs, UTC]              ┆ str                          ┆ str      ┆ u32          ┆ str        ┆ str        ┆ i32                   ┆ str           ┆ u64            ┆ u32           ┆ str     ┆ i64          ┆ i64            │
╞════════════════╪════════════════════════════════╪══════════════════════════════╪══════════╪══════════════╪════════════╪════════════╪═══════════════════════╪═══════════════╪════════════════╪═══════════════╪═════════╪══════════════╪════════════════╡
│ 1782864003     ┆ 2026-07-01 00:00:28.366841 UTC ┆ JA_C6-Weekday-118200_Q17_314 ┆ Q17      ┆ 1            ┆            ┆ 20260630   ┆ 0                     ┆ MTA NYCT_8440 ┆ 1782863999     ┆ 13            ┆ 501388  ┆ 1782864013   ┆ 1782864013     │
│ 1782864003     ┆ 2026-07-01 00:00:28.366841 UTC ┆ JA_C6-Weekday-118200_Q17_314 ┆ Q17      ┆ 1            ┆            ┆ 20260630   ┆ 0                     ┆ MTA NYCT_8440 ┆ 1782863999     ┆ 14            ┆ 501390  ┆ 1782864053   ┆ 1782864053     │
│ 1782864003     ┆ 2026-07-01 00:00:28.366841 UTC ┆ JA_C6-Weekday-118200_Q17_314 ┆ Q17      ┆ 1            ┆            ┆ 20260630   ┆ 0                     ┆ MTA NYCT_8440 ┆ 1782863999     ┆ 15            ┆ 501392  ┆ 1782864097   ┆ 1782864097     │
│ 1782864003     ┆ 2026-07-01 00:00:28.366841 UTC ┆ JA_C6-Weekday-118200_Q17_314 ┆ Q17      ┆ 1            ┆            ┆ 20260630   ┆ 0                     ┆ MTA NYCT_8440 ┆ 1782863999     ┆ 16            ┆ 501394  ┆ 1782864177   ┆ 1782864177     │
│ 1782864003     ┆ 2026-07-01 00:00:28.366841 UTC ┆ JA_C6-Weekday-118200_Q17_314 ┆ Q17      ┆ 1            ┆            ┆ 20260630   ┆ 0                     ┆ MTA NYCT_8440 ┆ 1782863999     ┆ 17            ┆ 501397  ┆ 1782864286   ┆ 1782864286     │
└────────────────┴────────────────────────────────┴──────────────────────────────┴──────────┴──────────────┴────────────┴────────────┴───────────────────────┴───────────────┴────────────────┴───────────────┴─────────┴──────────────┴────────────────┘

In [89]:
df.write_parquet(
    "raw/trip_updates/2026-07-01.parquet"
)

In [90]:
import polars as pl

url = (
    "http://parquet.gtfsrt.io/service_alerts"
    "/date=2026-07-01"
    "/base64url=aHR0cHM6Ly9ndGZzcnQucHJvZC5vYmFueWMuY29tL2FsZXJ0cw"
    "/data.parquet"
)

df = (
    pl.scan_parquet(url)
    .select([
        "feed_timestamp",
        "fetch_timestamp",
        "entity_id",
        "active_period_start",
        "active_period_end",
        "header_text",
        "description_text",
        "url",
        "route_id",
        "route_type",
        "stop_id",
        "trip_id",
        "trip_route_id",
        "trip_direction_id"
    ])
    .collect(engine="streaming")
)

print(df.shape)
print(df.head())

(208877, 14)
shape: (5, 14)
┌────────────────┬────────────────────────────────┬─────────────────────────────────┬─────────────────────┬───────────────────┬─────────────────────────────────┬─────────────────────────────────┬──────┬──────────┬────────────┬─────────┬─────────┬───────────────┬───────────────────┐
│ feed_timestamp ┆ fetch_timestamp                ┆ entity_id                       ┆ active_period_start ┆ active_period_end ┆ header_text                     ┆ description_text                ┆ url  ┆ route_id ┆ route_type ┆ stop_id ┆ trip_id ┆ trip_route_id ┆ trip_direction_id │
│ ---            ┆ ---                            ┆ ---                             ┆ ---                 ┆ ---               ┆ ---                             ┆ ---                             ┆ ---  ┆ ---      ┆ ---        ┆ ---     ┆ ---     ┆ ---           ┆ ---               │
│ u64            ┆ datetime[μs, UTC]              ┆ str                             ┆ u64                 ┆ u64               ┆ str                             ┆ str                             ┆ str  ┆ str      ┆ i32        ┆ str     ┆ str     ┆ str           ┆ u32               │
╞════════════════╪════════════════════════════════╪═════════════════════════════════╪═════════════════════╪═══════════════════╪═════════════════════════════════╪═════════════════════════════════╪══════╪══════════╪════════════╪═════════╪═════════╪═══════════════╪═══════════════════╡
│ 1782863956     ┆ 2026-07-01 00:00:20.367223 UTC ┆ MTA NYCT_lmm:planned_work:2224… ┆ 1735880435          ┆ 1798415688        ┆ X28&#x200c; and &#x200c;X38&#x… ┆ X28&#x200c; and &#x200c;X38&#x… ┆ null ┆ X38      ┆ null       ┆ null    ┆ null    ┆ null          ┆ null              │
│ 1782863956     ┆ 2026-07-01 00:00:20.367223 UTC ┆ MTA NYCT_lmm:planned_work:2224… ┆ 1735880435          ┆ 1798415688        ┆ X28&#x200c; and &#x200c;X38&#x… ┆ X28&#x200c; and &#x200c;X38&#x… ┆ null ┆ X28      ┆ null       ┆ null    ┆ null    ┆ null          ┆ null              │
│ 1782863956     ┆ 2026-07-01 00:00:20.367223 UTC ┆ MTA NYCT_lmm:planned_work:2781… ┆ 1769058000          ┆ 1798415688        ┆ Westbound M66 stop on E 68th S… ┆ Westbound M66 stop on E 68th S… ┆ null ┆ null     ┆ null       ┆ null    ┆         ┆ M66           ┆ 1                 │
│ 1782863956     ┆ 2026-07-01 00:00:20.367223 UTC ┆ MTA NYCT_lmm:planned_work:2781… ┆ 1769058000          ┆ 1798415688        ┆ Westbound M66 stop on E 68th S… ┆ Westbound M66 stop on E 68th S… ┆ null ┆ null     ┆ null       ┆ null    ┆         ┆ M66           ┆ 0                 │
│ 1782863956     ┆ 2026-07-01 00:00:20.367223 UTC ┆ MTA NYCT_lmm:planned_work:3082… ┆ 1774497600          ┆ 1798415688        ┆ Southbound B16 stops on 13th A… ┆ Southbound B16 stops on 13th A… ┆ null ┆ null     ┆ null       ┆ null    ┆         ┆ B16           ┆ 0                 │
└────────────────┴────────────────────────────────┴─────────────────────────────────┴─────────────────────┴───────────────────┴─────────────────────────────────┴─────────────────────────────────┴──────┴──────────┴────────────┴─────────┴─────────┴───────────────┴───────────────────┘

In [91]:
df.null_count()

shape: (1, 14)
┌────────────────┬─────────────────┬───────────┬─────────────────────┬───────────────────┬─────────────┬──────────────────┬────────┬──────────┬────────────┬─────────┬─────────┬───────────────┬───────────────────┐
│ feed_timestamp ┆ fetch_timestamp ┆ entity_id ┆ active_period_start ┆ active_period_end ┆ header_text ┆ description_text ┆ url    ┆ route_id ┆ route_type ┆ stop_id ┆ trip_id ┆ trip_route_id ┆ trip_direction_id │
│ ---            ┆ ---             ┆ ---       ┆ ---                 ┆ ---               ┆ ---         ┆ ---              ┆ ---    ┆ ---      ┆ ---        ┆ ---     ┆ ---     ┆ ---           ┆ ---               │
│ u32            ┆ u32             ┆ u32       ┆ u32                 ┆ u32               ┆ u32         ┆ u32              ┆ u32    ┆ u32      ┆ u32        ┆ u32     ┆ u32     ┆ u32           ┆ u32               │
╞════════════════╪═════════════════╪═══════════╪═════════════════════╪═══════════════════╪═════════════╪══════════════════╪════════╪══════════╪════════════╪═════════╪═════════╪═══════════════╪═══════════════════╡
│ 0              ┆ 0               ┆ 0         ┆ 0                   ┆ 25622             ┆ 0           ┆ 0                ┆ 208877 ┆ 152314   ┆ 208877     ┆ 208877  ┆ 56563   ┆ 56563         ┆ 56563             │
└────────────────┴─────────────────┴───────────┴─────────────────────┴───────────────────┴─────────────┴──────────────────┴────────┴──────────┴────────────┴─────────┴─────────┴───────────────┴───────────────────┘

In [92]:
df.write_parquet(
    "raw/service_alerts/2026-07-01.parquet"
)